service: ${file(config.json):name}

provider:
  name: aws
  runtime: nodejs4.3
  profile: ${file(config.json):provider.profile}
  stage: ${file(config.json):provider.stage}
  region: ${file(config.json):provider.region}

custom:
  webpackIncludeModules: false # enable auto including modules

plugins:
  - serverless-webpack

package:
  exclude:
    - .serverless
    - .webpack
    - coverage
    - .babelrc
    - .eslintignore
    - .eslintrc
    - .gitignore
    - LICENSE
    - package.json
    - README.md
    - serverless.yml
    - webpack.config.js


# you can add packaging information here
#package:
#  exclude:
#    - exclude-me.js
#  artifact: my-service-code.zip

functions:
  sharpImage:
    description: Resizes images
    memorySize: 1024
    timeout: 30
    handler: handler.processImage
    events:
      - s3:
        bucket: ${file(config.json):sourceBucket}
        event: s3:ObjectCreated:*
        rules:
          - prefix: ${file(config.json):sourcePrefix}

resources:
  Resources:
    imageSourceBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${file(config.json):sourceBucket}
    imageDestinationBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${file(config.json):destinationBucket}
