service: ${file(src/config.js):name}

provider:
  name: aws
  runtime: nodejs6.10
  profile: ${file(src/config.js):provider.profile}
  stage: ${file(src/config.js):provider.stage}
  region: ${file(src/config.js):provider.region}
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "s3:ListBucket"
         - "s3:GetObject"
         - "s3:GetObjectAcl"
       Resource:
         Fn::Join:
           - ""
           -  - "arn:aws:s3:::"
              - ${file(src/config.js):sourceBucket}
              - "/"
              - ${file(src/config.js):sourcePrefix}
              - "*"
    -  Effect: "Allow"
       Action:
         - "s3:ListBucket"
         - "s3:PutObject"
         - "s3:DeleteObject"
         - "s3:GetObjectAcl"
         - "s3:ListBucketMultipartUploads"
         - "s3:ListMultipartUploadParts"
         - "s3:PutObject"
         - "s3:PutObjectAcl"
         - "s3:PutObjectTagging"
         - "s3:PutObjectVersionAcl"
         - "s3:PutObjectVersionTagging"
       Resource:
         Fn::Join:
           - ""
           -  - "arn:aws:s3:::"
              - ${file(src/config.js):destinationBucket}
              - "/"
              - ${file(src/config.js):destinationPrefix}
              - "*"

custom:
  webpackIncludeModules: false # disable auto including modules

plugins:
  - serverless-webpack

package:
  exclude:
    - .serverless
    - .webpack
    - coverage
    - .babelrc
    - .eslintignore
    - .eslintrc
    - .gitignore
    - LICENSE
    - package.json
    - README.md
    - serverless.yml
    - webpack.config.js

functions:
  sharpImage:
    description: Resizes images
    memorySize: 1024
    timeout: 30
    handler: handler.processImage
    events:
      - s3:
          bucket: ${file(src/config.js):sourceBucket}
          event: s3:ObjectCreated:*
          rules:
            - prefix: ${file(src/config.js):sourcePrefix}

resources:
  Resources:
    imageDestinationBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${file(src/config.js):destinationBucket}
